# Generated by Django 3.0.14 on 2021-10-27 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nitrogen', models.PositiveIntegerField(null=True)),
                ('Phosphorus', models.PositiveIntegerField(null=True)),
                ('Potasium', models.PositiveIntegerField(null=True)),
                ('Temperature', models.FloatField(null=True)),
                ('Humidity', models.FloatField(null=True)),
                ('pH', models.FloatField(null=True)),
                ('Rainfall', models.FloatField(null=True)),
                ('predictions', models.CharField(blank=True, max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
