# Generated by Django 3.0.14 on 2021-11-01 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data',
            old_name='predictions',
            new_name='predictions_label',
        ),
    ]
