# Generated by Django 3.0.14 on 2021-11-01 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20211101_1307'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data',
            old_name='predictions_label',
            new_name='predictions',
        ),
    ]
