# Generated by Django 3.0.14 on 2021-11-01 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_data_predictions_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='Type',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='predictions_type',
            field=models.IntegerField(null=True),
        ),
    ]
