# Generated by Django 3.0.14 on 2022-08-04 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20211101_1321'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='Humidity',
        ),
        migrations.RemoveField(
            model_name='data',
            name='Nitrogen',
        ),
        migrations.RemoveField(
            model_name='data',
            name='Phosphorus',
        ),
        migrations.RemoveField(
            model_name='data',
            name='Potasium',
        ),
        migrations.RemoveField(
            model_name='data',
            name='Rainfall',
        ),
        migrations.RemoveField(
            model_name='data',
            name='Temperature',
        ),
        migrations.RemoveField(
            model_name='data',
            name='Type',
        ),
        migrations.RemoveField(
            model_name='data',
            name='pH',
        ),
        migrations.RemoveField(
            model_name='data',
            name='predictions_type',
        ),
        migrations.AddField(
            model_name='data',
            name='url',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
